apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-gitops-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AbhishekChoudhary23/DevOps-Observability-k8s-gitops-manifest.git'
    targetRevision: main
    path: .                 # Point directly to the root directory
    directory:
      recurse: true         # CRITICAL: Tells ArgoCD to look inside all subfolders recursively
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-gitops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true