apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - my-gitops-app
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: web
      path: /metrics
      interval: 10s