apiVersion: v1
kind: Namespace
metadata:
  name: my-gitops-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-backend
  namespace: my-gitops-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # CodePipeline will update this via sed
          image:123456789012.dkr.ecr.ap-south-1.amazonaws.com/observability-backend:latest
          ports:
            - containerPort: 5000 
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 250m
                  memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-gitops-app
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: web
      port: 5000
      targetPort: 5000